### ISSUE TITLE
BRAS flagged when 2nd argument is large but still valid

### ISSUE THREAD

**Issue by Jakub-CZ** [eclipse/che-che4z-lsp-for-hlasm#177]
**Describe the bug**
The valid range for branch addresses in `BRAS` is a half of what it should be.

**To Reproduce**
Code a `BRAS` instruction so that RI<sub>2</sub> falls between `X'4000'` and `X'7FFF'`.
The 2nd argument is falsely flagged as in error.

**Expected behavior**
The correct upper limit should be +65534 because the binary value represents _the number of **halfwords** that is added
to the address of the instruction_.
Similarly with the lower limit.

**Screenshots**
![image](https://user-images.githubusercontent.com/16313562/133254119-30d5dbf2-7819-422a-9ae6-8687d0b1b371.png)

**Platform**
 - Editor: VS Code 1.60.0
 - OS: Windows
 - Plugin version: 0.14.1

**Additional context**
(unrelated quote)

![image](https://user-images.githubusercontent.com/16313562/133255398-c9da61e6-64c6-41e2-9f66-9b65864832a6.png)

**Comment by slavek-kucera** [comment]
TEST(machine_instr_check_test, reloc_ImmS_out_of_range) should not produce any diagnostics.
