### ISSUE TITLE
Symbols are not recognized inside literals

### ISSUE THREAD

**Issue by genntt** [eclipse/che-che4z-lsp-for-hlasm#193]
**Symbols are not recognized inside literals.**
_E.g., 'Find All References' to X issued in line 1 returns no result._

![x](https://user-images.githubusercontent.com/92263314/136701812-184351d5-440f-44a4-8399-c98d6db7e3bf.png)

Platform
- Editor: VS Code Version 1.61.0
- OS: Microsoft Windows Version 10.0.19043.1237
- Plugin version: HLASM Language Support v0.14.1

**Comment by slavek-kucera** [comment]
Hello @genntt, thank you for reporting the issue.

The literal support is currently incomplete and limited mostly to validation of syntax.
