### ISSUE TITLE
Windows Defender Firewall has blocked the language_server.exe

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-hlasm#2]
Is this a normal behaviour? 

![Capture](https://user-images.githubusercontent.com/45042840/70924995-cbe94880-202a-11ea-81da-ee30b3f7e19f.PNG)

**Comment by michalbali256** [comment]
Yes, it is normal behaviour. We open a TCP port to communicate with macro tracer.

We should look into opening the port only for localhost, maybe then it will not be blocked by windows firewall.

**Comment by michalbali256** [comment]
Should be fixed by release 0.9.0 available on the marketplace
