### ISSUE TITLE
`&SYSNDX(1,1)` reports a false positive diagnostic

### ISSUE THREAD

**Issue by michalbali256** [eclipse/che-che4z-lsp-for-hlasm#212]
**Describe the bug**
Using `&SYSNDX` with subscripts is valid hlasm. 

**To Reproduce**
```
 MACRO
 MAC
 &SYSNDX(1,1)
 MEND 
 
 MAC
```
There is an error at ` &SYSNDX(1,1)`. It is valid on mainframe.

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/38988507/146410535-41bd2295-32cd-4ec9-afb3-268995973fe5.png)

**Platform**
 - Editor: VS Code 1.63
 - OS: Windows
 - Plugin version: 0.15.1

**Additional context**
It seems like the assembler treats SYSNDX (and possibly more system variables) more like macro parameters, while we treat it internally like C type variable symbol.

**Comment by slavek-kucera** [comment]
Based on my test, all currently supported "scalar" system variables exhibit this behavior.
