### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Cl4xt0r** [eclipse/che-che4z-lsp-for-hlasm#245]
- Issue Type: `Bug`
- Extension Name: `hlasm-language-support`
- Extension Version: `1.0.0`
- OS Version: `Linux x64 5.13.0-35-generic`
- VS Code version: `1.65.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning ```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 16512,
		"activateCallTime": 6,
		"activateResolvedTime": 2244,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "BroadcomMFD.hlasm-language-support",
				"_lower": "broadcommfd.hlasm-language-support"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by slavek-kucera** [comment]
Hello @Cl4xt0r,

could you please describe the actual problem you encountered?

**Comment by Cl4xt0r** [comment]
Dear Slavek-Kucera
Thank the team for fixing the JAVA HOME problem and “Sorry” for the delay in replying.I have been investigating the problem and searching for solutions. I am a returning COBOL programmer after 10yrs in retirement. I have re-badged with IBM and chose VS Code and Git as the base of my workstation, using Ubuntu v.20.04.1, but in the past I have always had a DBA, so it has been a challenging, but an enjoyable journey, all so I can work from home and soon I hope.
The problem is a known one, [see: https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fail ]

This has helped me to identify that the main problem is with my Node.js package manager NVM. When launched via a UI gesture, VS Code that starts a small process to run (or "resolve") the shell environment defined in my workstation by .bashrc file, to check which node version to auto-use based on .nvmrc and this is the one that takes most of the time to complete.
I have found a solution that proposes skipping that check and adding a default node to the path to replace the autoloaded node version for a faster access.
The proposed change is:

# Add default node to path
export PATH=~/.nvm/versions/node/v16.1/bin:$PATH

# Load NVM
export NVM_DIR=~/.nvm
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh" --no-use

RC note: my node version path is v16.1 (Not: v12.16.1 as in the guidance.)

However: when I attempt to open my shell's startup file in VS Code by typing ~/.bashrc,  I get the response “Permission denied” probably for good reason.

Any help would be appreciated.

Kind regards, Roy

________________________________

**Comment by slavek-kucera** [comment]
This is starting to sound less and less like the problem with the plugin.
By default, we are running the language server in a native process, so node version is really immaterial and we are not using java at all in the hlasm plugin.

I am still not clear on what is the actual problem you are experiencing.

**Comment by Cl4xt0r** [comment]
Hi. You are right, it is Linux creating the Shell environment that VS Code runs in. I have searched online and edited the program that creates it, to speed it up. Only just finished and the test worked O.K.

Thanks for your time. Please close the issue.

Roy
________________________________
