### ISSUE TITLE
Incorrect evaluation of logical operations with strings

### ISSUE THREAD

**Issue by jirimosinger** [eclipse/che-che4z-lsp-for-hlasm#263]
**Describe the bug**
Logical operations (`OR` and possible `AND`) containing strings are not evaluated correctly when there is no space between an operand and a string.

**To Reproduce**
```
&VAR    SETC 'E'
&BOOL   SETB ('&VAR'EQ'E'OR'&VAR'EQ'D'OR'&VAR'EQ'B')

        END
```

**Expected behavior**
`&BOOL` should evaluate to `TRUE`

**Platform**
 - Editor: VS Code 1.67.1
 - OS: Windows
 - Plugin version: 1.2.0

**Additional context**
The following statements evaluate to `TRUE` as expected:
```
&BOOL   SETB ('&VAR'EQ'E' OR '&VAR'EQ'D' OR '&VAR'EQ'B')
&BOOL   SETB ('&VAR' EQ 'E' OR '&VAR' EQ 'D' OR' &VAR'EQ'B')
&BOOL   SETB ('&VAR'EQ'E'OR'&VAR'EQ'D')
```

**Comment by slavek-kucera** [comment]
The root cause is confusion between parsing apostrophe and attributes.
