### ISSUE TITLE
Incorrect configuration problem

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-lsp-for-hlasm#264]
<img width="540" alt="The editor could not be opened due an unexpected error File " src="https://user-images.githubusercontent.com/19686979/170508866-622afacb-387b-496a-83d7-c95c1f34c0cf.png">

**Comment by slavek-kucera** [comment]
fixed by 7c7d7a07360c8245cf5732c6c1be5e9ae40983ad
