### ISSUE TITLE
Code page support

### ISSUE THREAD

**Issue by Simnbf** [eclipse/che-che4z-lsp-for-hlasm#27]
The syntax checker doesn't seem to recognise characters in the 1146 code page (UK English euro), for example the below code is fine (with $ symbol) but with a £ it flags a syntactical error.

<img width="584" alt="Screenshot 2020-04-09 at 10 48 35" src="https://user-images.githubusercontent.com/13423139/78882292-c7202880-7a4f-11ea-905e-ff5adf4b2743.png">

**Comment by asmelko** [comment]
Hi,

I am affraid that [IBM HLASM Reference](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.asma400/asmr102153.htm) states that it should not compile. £ is not an allowed character in the mentioned case. For this reason, the plugin chooses to produce syntactic error. This seems to be a correct behaviour.
