### ISSUE TITLE
EQUATES of the form <LABEL> EQU *-<OTHER LABEL> erreanously flagged as error

### ISSUE THREAD

**Issue by cybersorcerer** [eclipse/che-che4z-lsp-for-hlasm#40]
**Describe the bug**
The HLASM Plugin flags some Assembler equate statements Statements as error, but those are perfectly valid, no Assembly Errors at all. To see what i am Talking About, please have a look at the attached screen shots. The first Shows that it is flagged, the second shot Shows the error as detected by the Plugin. There is really not much more i can tell you.

**To Reproduce**
Put a sequence like the ones shown in the attached screenshots into your Code and you see what i am talking About.

**Expected behavior**
Since this is not an error it should not be flagged as one

**Screenshots**
![shot1](https://user-images.githubusercontent.com/33680802/80332233-8c3d3380-884a-11ea-8587-90c23e12afa1.PNG)

![shot2](https://user-images.githubusercontent.com/33680802/80332262-a0813080-884a-11ea-80de-003da9e86094.png)

**Platform**
 - Editor: VS Code/Theia 1.44.2
 - OS: Windows NT Version 1809 Build 17763.1158
 - Plugin version: 0.10.0

**Comment by cybersorcerer** [comment]
Hi Guys,
just curious, any News on this?

**Comment by asmelko** [comment]
Hello sorcerer,
sorry for the delay, I was working on your other issue :D.

I am afraid I can not reproduce the error on 0.10.0. Probably the error depends on something else than just the snipped you showed.

Can you provide the whole source?

**Comment by cybersorcerer** [comment]
Hi asmelko … LOL there will be some more i guess ;-). Unfortunately i have to ask the Company i am currently working for. I wrote the whole system for them, but it is their property. I get back to you asap, but it won't be before Monday (tomorrow is a holyday herre in germany)

**Comment by cybersorcerer** [comment]
Hi Adam,

as i now have your version of 0.10.0 i can't reproduce it either. See my comment in the SPM enhancement.

Greetings

Ronny

**Comment by asmelko** [comment]
Seems like the bug fixed itself :D
