### ISSUE TITLE
Possibility to analyse HLASM listings

### ISSUE THREAD

**Issue by guideabc** [eclipse/che-che4z-lsp-for-hlasm#49]
I noticed that it could be of great use to have some support to analyse HLASM listings in a more friendly way there, too!

Having the references and colors as we already have for sources can speed up the process of analysis there! 
Also, another improvement could be coloring parameters and their counterparts in the machine representation correspondingly (**41** _1_ 0 0000 **LA**    _R1_,0).

For now I don't think we have such features anywhere, so I keep analyzing old ways and sometimes needing to consult external references to complement information that could be already there

**Comment by michalbali256** [comment]
Thank you for your feedback!

I have a followup question:
1. Do you expect that the HLASM extension generates the listing from hlasm source?
or 
2. Do you want to download the listing from mainframe?

Either way, implementing the feature basically means adding support for a new language "HLASM listing".

In my opinion, the current priority is to finish the features we already provide. But it is definitely a nice feature for the future. Do you know side-by-side editing of markdown documents in VS Code where on the left is the source and on the right is the preview of the markdown? I am wondering whether the extension could leverage the approach so the user could see both hlasm source and the listing side by side. Listing would be updated in real time, of course.

And one last question: What is the most frequent informations you look up in the listing? Maybe we could add the information to our hover/macro tracer to avoid using listing at all.

**Comment by guideabc** [comment]
Hello

About the questions:

1. Not exactly. Not sure if it would be necessary, indeed. After the code
is ready, it could just be properly assembled and generate the listing as
usual;

2. Yes, that was the case. After bringing up a listing, I opened it in VS
Code and if I had the colors differentiation, other references that are
already present in the HLASM configuration and, maybe, some extra features*
for listing only it would be extra helpful in its analysis than just
opening it and reading as usual.
* another feature I could think of was some corresponding between the
mnemonic codes and their machine codes, for example: CLI D1(B1),I2 ->
95IIBDDD -> 95 = CLI, II = I2, D1(B1)=BDDD (supposing for some reason it
wasn't obvious what part of the machine was corresponding to the immediate
or to the address representation).

I think the most frequent thing to me is to be sure what are the current
base registers being used for some variable fields/addresses and their
actual displacements in addition to the base. Sometimes looking only at the
source code it happens to get lost if there are many USINGs, DROPs,
overlapping areas and similar things...
Also, for "data areas", sometimes the listing shows some gaps / fillings
that are generated due to data types and someone could not be aware of it
(for example, alignment for quad/double/full/half boundaries: DS CL1, then
DS F, that could generate 3 bytes between both fields).

And about that you said about previewing, yeah, that could be interesting,
too

Kind regards,
Guilherme
