### ISSUE TITLE
EXRL instruction flagged as error by plugin

### ISSUE THREAD

**Issue by cybersorcerer** [eclipse/che-che4z-lsp-for-hlasm#57]
Hi guys,

have a look at the following code fragment:
```
*-B E G I N-----------------------------------------------------------*
*  Move command from CIB to internal buffer                           *
*---------------------------------------------------------------------*
             MVIY  CMDBUFF,C' '              Clear command buffer
             MVC   CMDBUFF+1(L'CMDBUFF-1),CMDBUFF
             LAY   R1,CMDBUFF                Load command pointer$02$06
             LAY   R2,CIBDATA                  Load A(MODIFY/F data). $06
             BCTR  R3,0                             Decrement it for MVC.
             EXRL  R3,MVCEX                    Changed to EXRL        $06
*-E N D---------------------------------------------------------------*
*  Move command from CIB to internal buffer                           *
*---------------------------------------------------------------------*
              .
              .
MVCEX  MVC   0(0,R1),0(R2)                 Move command to internal

```

The EXRL instruction above is perfectly valid. MVCEX is a label in code. EXRL is of format RIL-b and available since z10. MVCEX in the instruction is converted to the number of halfwords distance between the EXRL instruction address and the MVCEX label.
The plugin marks this instruction with the following error:

**Error at EXRL instruction: operand must be an absolute immediate value"**

This is wrong and should be fixed!
	
 - Editor: VS Code/Theia 1.45.1
 - OS: Windows 10 64-Bit
 - Plugin version: 0.11.0

greetings

Ronny

**Comment by slavek-kucera** [comment]
Resolved in release 0.14.0.
