### ISSUE TITLE
HLASM structured macros (e.g. IF, ELSE, ENDIF) are not recognized.

### ISSUE THREAD

**Issue by Mstebner-PKWARE** [eclipse/che-che4z-lsp-for-hlasm#58]
The HLASM provides a suite of structured macros that apparently are not recognized or found through the HLA.SASMMAC1 & HLA.SASMMAC2 macro members, since they are not explicit members matching the names (IF, DO, etc).

**To Reproduce**
1. Provide the members of HLA.SASMMAC1 & 2 in the proc_grps.json libs: directories.
2. Use ASM source members that use the HLASM macro suite
3. All structured macros are flagged in error.

**Expected behavior**
The structure logic macros should be recognized and not flagged in error.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44708995/84194581-3a9fdf80-aa6b-11ea-878f-0e92b69ef25c.JPG)
![Capture](https://user-images.githubusercontent.com/44708995/84194819-9a968600-aa6b-11ea-97f0-a4803ce9e255.JPG)

**Platform**
 - OS: z/OS
 - Plugin version: 0.11.0

**Additional context**

**Comment by asmelko** [comment]
Hi, 

these macros are in SASMMAC2. To use them, you need to write `COPY  ASMMSP` before the first use of these macros. See the IBM documentation [here](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.asmk200/asmtug2108.htm).

If  writing `COPY  ASMMSP` did not help, can you provide us with the whole source code where the error occured? 

Regards.

**Comment by Mstebner-PKWARE** [comment]
Yes, an explicit COPY ASMMSP in the source code was required (and worked).  We had been using PROFILE(ASMMSP) as an assembler option, which provides an implicit COPY ASMMSP during an actual compile.
