### ISSUE TITLE
Disable colorization of whitespace characters

### ISSUE THREAD

**Issue by JeffyOLOLO** [eclipse/che-che4z-lsp-for-hlasm#6]
Hello!

I work with enabled `"editor.renderWhitespace": "all"` option.
But the extention colorizes whitespace characters (see comment or next continuation line spaces):
![image](https://user-images.githubusercontent.com/34167060/72145270-d3d6a700-33a2-11ea-9390-1487ec4a1f79.png)

Is there any way to avoid this?

Thank you!

**Comment by michalbali256** [comment]
At the moment, I do not see any workaround.

There is an issue regarding this behaviour on the VS Code project
https://github.com/Microsoft/vscode/issues/49462

**Comment by JeffyOLOLO** [comment]
Oh, thank you for the link.
I'm closing this issue.
