### ISSUE TITLE
Cache macro and copy files during editing

### ISSUE THREAD

**Issue by asmelko** [eclipse/che-che4z-lsp-for-hlasm#68]
**Describe the solution you'd like**
Currently, when a file is changed, a program with all of its dependencies (macro and copy files) is reparsed. This may be a parsing bottleneck that increases the response time of the plugin.

It could be useful to parse only such dependencies that got actually changed.

**Acceptance criteria**
- [ ] When user changes an opencode, only the opencode file is reparsed.
- [ ] When user changes a macro or copy file, only the opencode file and the changed file are reparsed.

**Comment by michalbali256** [comment]
Implemented by #129
