### ISSUE TITLE
Allow wildcards to be specified in the proc_grps settings for macro resolution across multiple folders

### ISSUE THREAD

**Issue by jwrey01** [eclipse/che-che4z-lsp-for-hlasm#69]
Our product distributes its macros across multiple folders.  Each project a person works on will mirror the folder structure.  

In order to resolve the COPY and macro usage, each distinct folder that has macros must be added to proc_grp. This is a lot of typing, time-consuming and error-prone.  

Being able to specify wildcards in place of folders would be ideal, such as /TL1/*/SSF1/*

In the example, "TL1" is the top layer for a project I am working on.  TL2 would be a different project and so on.

The folder structure underneath is the same across all of the projects.  The second layer distributes the product into ~100 components, so a wild-card is preferred here.  The SSF1 folder is a fixed name.  After SSF1, there are 4-5 other folders that each could contain macros.   So, the enumeration of the specific directories that would need to be provided is 400-500.

**Comment by michalbali256** [comment]
Hello,

We were discussing this issue and we realized that there may be a problem, when there is a macro with the same name in several libraries expanded by a wildcard. Currently, there is no such problem, since we just take the macro that is in a folder that is specified first in the list of processor groups.

What would be the expected resoultion in such case according to your project? Or do you have all macros with unique names across all folders?

**Comment by jwrey01** [comment]
In our case, ultimately, there can only be one instance of a part name across all of the product's base set of folders.   If this were not the case, then which part is correct and gets used would be an issue.

However, a developer needs to be able to change a macro, so during development of that change they will have a copy of that macro (with their differences) that would need to be found ahead of the product's version of that macro.  So, existing part "A" is changed by a developer.  During the developer's work on that part, their version of "A" should always be used ahead of the product's version of "A".  When the developer finishes, their version of "A" will replace the base version of "A".  At that point, there is just one version of "A" in some product folder.  I think this will appear as the developer changing the part in the folder it resides in, and not changing the part outside of that structure so it won't really be duplicate parts but the only part of its name in the set of folders that developer is using.   So, part "A" is in /SSF99/.  Developer "checks out" the part, so it resides in their /TL1/SSF99/ location.  This may appear to the tooling as the only instance of the part, which is fine.  Once done, the part is delivered from /TL1/ to the base, but it resides in /SSF99/.  No issues.

It also is quite plausible that a developer will want to create a new macro, and is unaware of the full set of macros in the product (complex, too many folders, etc.) and so they choose "A" as the name for their new macro and /SSF1/ as the place it is to reside.  Their "A" may be found and used during their use and they will ultimately deliver their version of "A" into the product's /SSF1/ folder.  This is a conflict that should not happen - the same part name in the product across multiple folders.   It is best to catch this as soon as it happens - duplicate part across different folders.

So, in the first case of changing the pre-existing part, duplicates (if that is how the tooling sees it) should be allowed between the developer's set of folders and the product's set of folders as long as the part is in the same-named folder.   In the second case, duplicates should not be allowed across different folders.
