### ISSUE TITLE
Assembler programs are not highlighted immediately

### ISSUE THREAD

**Issue by radecek9787** [eclipse/che-che4z-lsp-for-hlasm#7]
When I open an HLASM program in VS Code, it does not recognize it is HLASM so it is not highlighted automatically. I always need to switch it to highlight HLASM manually.

**Comment by marcel1hruska** [comment]
Hi!

Sorry to keep you waiting. Today, we released version 0.10.0, which brings new capabilities for the detection of HLASM files. Every file configured as a program or as a part of a processor group is now recognized as HLASM. 

Furthermore, you may fill the `alwaysRecognize` array inside `pgm_conf.json` with your own wildcards that also match HLASM files. A usage example can be found in the updated readme.

Please note that the automatic detection feature is now considered as a fall-back option, in case none of the options above work for you.
