### ISSUE TITLE
Specify compiler options

### ISSUE THREAD

**Issue by asmelko** [eclipse/che-che4z-lsp-for-hlasm#73]
**Is your feature request related to a problem? Please describe.**

Many HLASM programs rely on flags and system variables that are specified by compiler options. (i.e., `SYSPARM`, `MACROCASE`, `DBCS`, ...).

**Describe the solution you'd like**

Find a way to provide user with the ability to specify compiler options.

**Describe alternatives you've considered**

In MF, the options for compiler are specified separately for each processor group.
We can provide the behavior by adding the system variables to each processor group in `proc_grps.json`.

**Comment by michalbali256** [comment]
It is now possible to specify `SYSPARM`. Leaving the rest of the options to separate issues.
