### ISSUE TITLE
Extension Does Not Work with VS Code Color Theme 

### ISSUE THREAD

**Issue by dkelosky** [eclipse/che-che4z-lsp-for-hlasm#82]
**Describe the bug**
The HLASM uses fixed colors for instructions which forces uses to select a theme that is readable for this extension.  

**To Reproduce**
Change color preferences from light to dark to any other build-in or addon theme.  

**Expected behavior**
The HLASM extension should honor theme settings in VS Code

**Screenshots**
Changing color preferences in VS Code has no effect on colors within the HLASM editor.  

![colors](https://user-images.githubusercontent.com/14940561/91857009-4ef01480-ec35-11ea-9d25-b54ba5c0868d.gif)

**Platform**
 - Editor: VS Code
 - OS: Windows 10
 - Plugin version:  0.11.0

**Additional context**

**Comment by zimlu02** [comment]
Hi Dan, 
thank you for creating this issue, Marcel is already working on it. Good to track it here though.
