### ISSUE TITLE
LANGUAGE_SERVER.EXE has not been allowed to run

### ISSUE THREAD

**Issue by EmlynWill** [eclipse/che-che4z-lsp-for-hlasm#96]
**Describe the bug**
At our site with virtual "locked down" desktops we can not use the HLASM extension because of this error "LANGUAGE_SERVER.EXE has not been allowed to run". We can not run .exe files.

**To Reproduce**
Enable HLASM Language Support on our virtual desktop,

**Expected behavior**
"LANGUAGE_SERVER.EXE has not been allowed to run" error message

**Screenshots**

**Platform**
 - Editor: VS Code/Theia (including version)
 - OS: [e.g. iOS] (including distro)
 - Plugin version: [e.g. 0.10.0]

**Additional context**

**Comment by VitGottwald** [comment]
Thank you for trying out our extension @EmlynWill! Could you help us better understand the restricted environment so that we could address it?

Would it be sufficient if we signed the the binary with a developer certificate, so that it would come from a known developer, rather than being an unknown `.exe` file?

**Comment by EmlynWill** [comment]
I don't have enough knowledge of how our desktops are set up but we could certainly try it.

**Comment by VitGottwald** [comment]
If we prepared a signed version of the extension in a VSIX file, would you be able to install it to try it out?

**Comment by EmlynWill** [comment]
Ye, if you give me the instructions

**Comment by VitGottwald** [comment]
Here is a VSIX file that is signed by a Broadcom certificate to try out [hlasm-language-support-0.11.1.zip](https://github.com/eclipse/che-che4z-lsp-for-hlasm/files/5652915/hlasm-language-support-0.11.1.zip).

I had to change the extension from `.vsix` to `.zip` so that github would accept it. Please, change the extension back from `.zip` to `.vsix`.

[Here are the instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) for installing the VSIX file. In case something is not clear, please, let us know!

**Comment by VitGottwald** [comment]
Whenever you have the time to test it @EmlynWill, we will be happy to hear from you!

**Comment by EmlynWill** [comment]
Unfortunately that did not work

**Comment by VitGottwald** [comment]
@EmlynWill were you able to install it and it got rejected by windows security policy? Or did you run into problems with installation?

**Comment by EmlynWill** [comment]
The installation didn't issue any errors so I assume that it installed ok, although I don't know how to prove it. I got the same "LANGUAGE_SERVER.EXE has not been allowed to run" error message after the install.

**Comment by VitGottwald** [comment]
One way of verifying it could be uninstalling the extension first and making sure it is not there. Then trying to install it from the VSIX file. If you get the same error again, it means that the installation from VSIX succeeded, but the signing of the binary did not help.

**Comment by EmlynWill** [comment]
I uninstalled it, then "code --install-extension hlasm-language-support-0.11.1.vsix"
But "HLASM Language Support" doesn't show up on my installed extensions list (even after a restart of VSCode)

**Comment by VitGottwald** [comment]
Can you try installing it from the UI?

**Comment by EmlynWill** [comment]
UI? I was installing it from the VSCode terminal

**Comment by VitGottwald** [comment]
When you press `Ctrl+Shift+P` a command palette should show up. Typing in `Install from VSIX` should filter the list of commands down to the _Install from VSIX..._ command. Then by hitting enter, a dialog should open where you would select the VSIX file to be installed.

**Comment by EmlynWill** [comment]
Got it, and installed this time. 
"LANGUAGE_SERVER.EXE has not been allowed to run"

**Comment by zimlu02** [comment]
Hi Emlyn,

please check whether you don't have checked auto-updates in VSC settings - this way the custom VSIX file will always get overwritten with the one available on VSC Marketplace.

<img width="815" alt="Screenshot 2020-12-09 at 11 02 24" src="https://user-images.githubusercontent.com/38490125/101615294-41091700-3a0e-11eb-89ed-1929efa3c02f.png">

**Comment by VitGottwald** [comment]
If I remember correctly, @EmlynWill said that they have a locked down version of VSCode without access to the market place.

But it might still be good to check for the vscode settings, just in case.

**Comment by VitGottwald** [comment]
So what I see now, is that the signature did not help. At this point it is not clear to me how to resolve this issue.

The extension is written in C++ and compiled for each platform (Windows, Linux, macOS) as a native binary. It is then packaged into the extension format of VSCode. When you open an assembler file, a language server (LANGUAGE_SERVER.EXE) is started to do the analysis of the assembler code and provide code assistance like navigation, completion and instruction hints to the editor.

It looks like we will need a guidance from your IT department how to make our extension compliant with your internal policies. Could you, please, reach out to them and let us know?

**Comment by EmlynWill** [comment]
Hi Lukas, I do not have auto updates set.
Vit - We can install extensions from the marketplace,

**Comment by VitGottwald** [comment]
Thank you for checking the settings and trying the installation from VSIX @EmlynWill . Do you think you can talk with your IT department to help us with this issue?

**Comment by EmlynWill** [comment]
I'll try with them again

**Comment by VitGottwald** [comment]
Thank you @EmlynWill!

**Comment by EmlynWill** [comment]
I contacted our helpdesk can't help. We can not run unpackaged .exe files.

**Comment by VitGottwald** [comment]
Would it be possible to get our extension "packaged" then?

**Comment by EmlynWill** [comment]
We can try, the process takes a long time though.

**Comment by michalbali256** [comment]
Hi Emlyn,
The latest version of the extension should support your use case now. First, it will try to start the .exe file, which will fail, after several seconds, there should be a popup that suggests using WASM version of the language server, which runs under Node.js

Please let us know if it works for you, so we could close this issue.

**Comment by EmlynWill** [comment]
Hi Michal, yes it works for us. Thank you for your help
